// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'API=KEY',
    appId: '1:32999909244:web:8fcc83b1e69a74998ce6f9',
    messagingSenderId: '32999909244',
    projectId: 'transit-pay-kenya',
    authDomain: 'transit-pay-kenya.firebaseapp.com',
    storageBucket: 'transit-pay-kenya.firebasestorage.app',
    measurementId: 'G-T5GJB2C4HC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'API=KEY',
    appId: '1:32999909244:android:44dd7315901dd8488ce6f9',
    messagingSenderId: '32999909244',
    projectId: 'transit-pay-kenya',
    storageBucket: 'transit-pay-kenya.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'API=KEY',
    appId: '1:32999909244:ios:c8902e98f13a3ea28ce6f9',
    messagingSenderId: '32999909244',
    projectId: 'transit-pay-kenya',
    storageBucket: 'transit-pay-kenya.firebasestorage.app',
    iosBundleId: 'com.example.transitPay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'API=KEY',
    appId: '1:32999909244:ios:c8902e98f13a3ea28ce6f9',
    messagingSenderId: '32999909244',
    projectId: 'transit-pay-kenya',
    storageBucket: 'transit-pay-kenya.firebasestorage.app',
    iosBundleId: 'com.example.transitPay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'API=KEY',
    appId: '1:32999909244:web:0018686a409b61f38ce6f9',
    messagingSenderId: '32999909244',
    projectId: 'transit-pay-kenya',
    authDomain: 'transit-pay-kenya.firebaseapp.com',
    storageBucket: 'transit-pay-kenya.firebasestorage.app',
    measurementId: 'G-FJLHGM89H5',
  );
}
